#!/bin/bash

set -e

i=$1

# --- environment ---
source /opt/detector/epic-main/bin/thisepic.sh
source /opt/local/bin/eicrecon-this.sh

config="9x130"
export DETECTOR_CONFIG="epic_craterlake_${config}"
export DETECTOR_PATH_NAME="${DETECTOR_PATH}/${DETECTOR_CONFIG}.xml"

SIGDIR="/w/work6/home/gp140f/9x130_ddvcs_ee_hplus/rootfiles"
BGDIR="/w/work6/home/gp140f/brems_9x130/rootfiles"
WORKDIR="/w/work6/home/gp140f/tcs_bg_merge"

MERGEDIR="${WORKDIR}/merge_out/"
OUTDIR="${WORKDIR}/recon_out/"
LOGDIR="${WORKDIR}/logs"
YAMLDIR="${WORKDIR}/yaml"

mkdir -p "${MERGEDIR}" "${OUTDIR}" "${LOGDIR}" "${YAMLDIR}"

SIGFILE="${SIGDIR}/9x130_ddvcs_ee_hplus_${i}.edm4hep.root"
BGFILE="${BGDIR}/brems_9x130_${i}.edm4hep.root"

SEGFILE="${MERGEDIR}/seg_${i}.edm4hep.root"
OUTFILE="${OUTDIR}/reco_seg_${i}.root"
MERGELOGFILE="${MERGEDIR}/seg_${i}.log"
LOGFILE="${LOGDIR}/recon_${i}.log"
YAMLFILE="${YAMLDIR}/seg_${i}.yml"

#echo "[Seg $i] Starting"

cd "${WORKDIR}" || exit 1


# ----------------------------------------
# Step 1: timeframe_builder (safe)
# ----------------------------------------
if [[ -s "${SEGFILE}" ]]; then
    echo "[Seg $i] Merge file exists, skipping timeframe_builder: ${SEGFILE}"
else
    if [[ ! -f "${YAMLFILE}" ]]; then

	BG_START=$(( i * 200 ))
	BG_END=$(( BG_START + 199 ))

	cat > "${YAMLFILE}" <<EOF
# Autogenerated
max_events: 10000
timeframe_duration: 2000.0
bunch_crossing_period: 10.0
introduce_offsets: true

sources:
  - name: signal
    input_files:
      - ${SIGFILE}
    static_number_of_events: true
    static_events_per_timeframe: 1
    use_bunch_crossing: true
    generator_status_offset: 0

  - name: brem_bg
    input_files:
EOF
	
	for ((bg=${BG_START}; bg<=${BG_END}; bg++)); do
            echo "      - ${BGDIR}/brems_9x130_${bg}.edm4hep.root" >> "${YAMLFILE}"
	done
	
    cat >> "${YAMLFILE}" <<EOF
    static_number_of_events: false
    mean_event_frequency: 1.0
    use_bunch_crossing: true
    generator_status_offset: 2000
EOF

    fi
    
    echo "[Seg $i] Running timeframe_builder"
    /home/gp140f/TimeframeBuilder/install/bin/timeframe_builder \
	--config "${YAMLFILE}" \
	-o "${SEGFILE}" \
	> "${MERGELOGFILE}" 2>&1
fi


# ----------------------------------------
# Step 2: eicrecon (safe)
# ----------------------------------------
if [[ -s "${OUTFILE}" ]]; then
    echo "[Seg $i] Reco output exists, skipping eicrecon: ${OUTFILE}"
else
    echo "[Seg $i] Running eicrecon"
    eicrecon \
	-Pjana:nevents=-1 \
	-Pdd4hep:xml_files=${DETECTOR_PATH_NAME} \
	${SEGFILE} \
	-Ppodio:output_file=${OUTFILE} \
	> ${LOGFILE} 2>&1
fi
echo "[Seg $i] Done"
``
